//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 09:29:06 AM IST 
//


package sbilife.com.pointofsale_bancaagency.ekyc.request;

import org.simpleframework.xml.Root;

@Root(name = "Demo")
public class Demo {
}
